### ISSUE TITLE
EF fiddle

### ISSUE THREAD

**Issue by natemcmaster** [bricelam/EFCore.VisualStudio#10]
Create a design-time webpage that users could use to play with EF.
### Usage

``` c#
public class Startup
{
     public void Configure(IAppBuilder app)
     {
          app.UseEntityFrameworkFiddle("/ef-fiddle");
     }
}
```

Creates a web page at `/ef-fiddle` where users can play around with an instance of DbContext.

Possible results we could visualize:
- SQL output that was generated
- Inspect the IModel #7
- Inspect the DDL to create the tables #5
- Visual representation of entity types and how they relate (possibly implemented in browser with [d3js](https://d3js.org/)
- Show actual data from query output

![presentation1](https://cloud.githubusercontent.com/assets/2696087/15941191/d7d4ba86-2e33-11e6-929d-7cc554ea469f.jpg)

Code editor could stub out a "playground"

``` c#
public FiddleResult Do(MyDbContext db)
{
     return FiddleResult.ShowQueryPlan(db => db.Blogs.Where( b=>b.Name == "Web"));
}
```

**Comment by ErikEJ** [comment]
Possible in LinqPad...

**Comment by natemcmaster** [comment]
This issue is stale. I have no plans to build something like this.

**Comment by bricelam** [comment]
😄 This repo is stale
