### ISSUE TITLE
Migrations UI

### ISSUE THREAD

**Issue by bricelam** [bricelam/EFCore.VisualStudio#3]
@rowanmiller put together some nice slides on this a while back...

**Comment by ErikEJ** [comment]
@bricelam Maybe something to consider for EF Core Power Tools - are you able to share the slides (privately, even) ?

**Comment by bricelam** [comment]
We never found them, but it looked something like this:

![image](https://user-images.githubusercontent.com/1226749/37183375-9667ef8e-22ea-11e8-97db-02fe05e1ed31.png)

I seem to remember a few different actions:
* Apply migrations if any aren't applied (shown above)
* Add a migration if there are pending model changes. Needs a way to specify the migration name too.
* Everything is up-to-date. (May need a unicorn picture here. 😉)

**Comment by rowanmiller** [comment]
@bricelam I found the deck with that the mock up was in - I emailed it to you.

**Comment by ErikEJ** [comment]
I understand that I can use the following APIs for this:
Check for any pending migrations: context.Database.GetPendingMigrations
Apply migrations: context.Database.Migrate

But how do I check for pending model changes??

**Comment by bricelam** [comment]
[This code](https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore/DatabaseErrorPageMiddleware.cs#L141-L143) does it.

**Comment by ErikEJ** [comment]
Excellent - WIP on the EF Core Power Tools side: https://github.com/ErikEJ/SqlCeToolbox/commit/8e9a636b9b020fdcb1dd52a349346b7152c13289

**Comment by bricelam** [comment]
Closing. We'll use ErikEJ/SqlCeToolbox#649 to track the feature.
